TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devHV.db
DB_INSTALLS += $(TOP)/HVSup/devHV.proto

DB_INSTALLS += devHeinz.db
DB_INSTALLS += $(TOP)/HVSup/devHeinz.proto

#$(info DB_INstalls is $(DB_INSTALLS))

#=======================================
include $(TOP)/configure/RULES
